services:

  postgres:
    image: postgres:16
    container_name: ajt-postgres
    environment:
      POSTGRES_DB: ajt_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5454:5432"
    volumes:
      - ajt_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ajt_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./api
    container_name: ajt-backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ajt_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  ajt_data: